name = "PSRGraf"
uuid = "5d241258-a465-4fe4-891f-4b2030ea640f"
version = "0.1.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Encodings = "8275c4fe-57c3-4fbf-b39c-271e6148849a"

[compat]
Dates = "1"
Encodings = "0.1.1"
julia = "1.10"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV", "DataFrames", "Test"]